name: hub_finder
description: Find user, repos and organizations in your phone.

publish_to: "none"

version: 2.0.0+30

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  share_plus: ^10.0.2
  path_provider: ^2.1.4
  dio: ^5.7.0
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  hive: ^2.2.3
  in_app_review: ^2.0.9
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.3
  flutter_animate: ^4.5.0

  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  firebase_performance: ^0.11.1+2
  firebase_in_app_messaging: ^0.9.0+4
  firebase_messaging: ^16.0.4
  firebase_core: ^4.2.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.2.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/

